version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:10-browsers
    working_derectory: ~/repo
    steps:
      - run:
          name: install node_modules
          command: yarn install
      - run:
          name: build
          command: yarn run build
      - run:
          name: install awscli
          command: |
            sudo apt-get update
            sudo apt-get install -y python-dev
            sudo curl -O https://bootstrap.pypa.io/get-pip.py
            sudo python get-pip.py
            sudo pip install awscli --upgrade
            aws --version
            aws s3 ls
      - run:
          name: deploy to s3
          command: aws s3 sync build/ s3://hosting-effective-work-frontend --delete
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
